version: '3.8'

services:
  tests:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: saucedemo-tests
    environment:
      - BROWSER=chrome
      - HEADLESS=true
      - TIMEOUT=20
      - BASE_URL=https://www.saucedemo.com
    volumes:
      - ./results/allure-results:/app/results/allure-results
      - ./results/screenshots:/app/results/screenshots
      - ./logs:/app/logs
    networks:
      - test-network

  allure:
    image: frankescobar/allure-docker-service
    container_name: allure-report
    environment:
      - CHECK_RESULTS_EVERY_SECONDS=3
      - KEEP_HISTORY=1
    ports:
      - "5050:5050"
    volumes:
      - ./results/allure-results:/app/allure-results
      - ./reports/allure-report:/app/default-reports
    depends_on:
      - tests
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
